import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    paddingTop: 8,
    paddingBottom: 16,
    paddingHorizontal: 16,
    minHeight: 60, 
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap', 
  },
  appName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff', 
    flexShrink: 1, 
  },
  appTagline: {
    fontSize: 13,
    color: '#ffffff',
    opacity: 0.9,
    flexShrink: 1,
    lineHeight: 18, 
  },
  logo: {
    fontSize: 56,
    textAlign: 'center',
    marginBottom: 14,
    color: '#ffffff',
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  content: {
    padding: 16,
    paddingBottom: 80,
  },
  welcomeSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  greeting: {
    fontSize: 22,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 6,
    textAlign: 'center', 
    lineHeight: 28, 
  },
  welcomeText: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 8, 
  },
  scoreCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    minHeight: 100, 
  },
  scoreTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 10,
    textAlign: 'center',
    lineHeight: 22,
  },
  progressContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  progressNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  progressLabel: {
    fontSize: 11,
    color: '#6b7280',
    lineHeight: 14,
  },
  progressBarContainer: {
    width: '100%',
    height: 7,
    backgroundColor: '#e5e7eb',
    borderRadius: 3,
    marginTop: 6,
  },
  progressBar: {
    height: 7,
    backgroundColor: '#008080',
    borderRadius: 3,
  },
  scoreMessage: {
    fontSize: 13,
    color: '#10b981',
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 8,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 10,
    lineHeight: 20,
  },
  metricCard: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: 100, 
  },
  metricIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    alignSelf: 'center',
  },
  metricEmoji: {
    fontSize: 16,
  },
  metricTitle: {
    fontSize: 11,
    fontWeight: '500',
    color: '#6b7280',
    marginBottom: 3,
    textAlign: 'center',
    lineHeight: 14,
    numberOfLines: 2, 
  },
  metricValue: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 3,
    justifyContent: 'center',
  },
  metricNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  metricUnit: {
    fontSize: 9,
    color: '#6b7280',
    marginLeft: 3,
  },
  metricStatus: {
    fontSize: 9,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 12,
  },
  primaryButton: {
    borderRadius: 10,
    marginBottom: 10,
    paddingVertical: 14, 
    paddingHorizontal: 16,
    alignItems: 'center',
    minHeight: 44, 
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 18,
  },
  secondaryButton: {
    backgroundColor: '#ffffff',
    paddingVertical: 14, 
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    minHeight: 44, 
  },
  secondaryButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
    lineHeight: 16,
  },
  progressItem: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  progressDate: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 6,
    lineHeight: 20,
  },
  progressMetrics: {
    flexDirection: 'column',
  },
  progressMetric: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 3,
    lineHeight: 18,
  },
  inputContainer: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1f2937',
    marginBottom: 6,
    lineHeight: 18,
  },
  input: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    fontSize: 13,
    minHeight: 42,
    textAlignVertical: 'center',
  },
  picker: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    fontSize: 13,
    minHeight: 42, 
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start', 
    marginBottom: 16,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#6b7280',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
    marginTop: 2, 
  },
  checkboxChecked: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  checkboxText: {
    color: '#ffffff',
    fontSize: 14,
  },
  checkboxLabel: {
    fontSize: 13,
    color: '#1f2937',
    lineHeight: 18,
    flex: 1, 
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap', 
  },
  welcomeHeader: {
    backgroundColor: '#008080',
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: height * 0.35,
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  illustrationContainer: {
    width: 180,
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIllustration: {
    width: '100%',
    height: '100%',
  },
  welcomeAppName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 6,
    letterSpacing: 1,
    textAlign: 'center',
    lineHeight: 34,
  },
  welcomeTagline: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    fontWeight: '400',
    lineHeight: 20,
    paddingHorizontal: 16, 
  },
  welcomeContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 32,
  },
  welcomeMessageContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  welcomeTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 10,
    textAlign: 'center',
    lineHeight: 30,
  },
  welcomeDescription: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 16,
  },
  welcomeSection: {
    marginBottom: 28,
  },
  welcomeSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  pickerContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  welcomePicker: {
    height: 54,
    paddingHorizontal: 14,
  },
  privacyContainer: {
    marginBottom: 28,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 4,
  },
  modernCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    marginTop: 2,
    backgroundColor: '#ffffff',
  },
  modernCheckboxChecked: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  checkmarkIcon: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  privacyText: {
    fontSize: 12,
    color: '#4b5563',
    lineHeight: 30,
    flex: 1,
  },
  linkText: {
    color: '#008080',
    fontWeight: '600',
  },
  getStartedButton: {
    backgroundColor: '#008080',
    paddingVertical: 16,
    paddingHorizontal: 20, 
    borderRadius: 14,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#008080',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    minHeight: 50, 
  },
  disabledButton: {
    backgroundColor: '#b2d8d8',
    shadowOpacity: 0,
    elevation: 0,
  },
  getStartedButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 20,
  },
  disabledButtonText: {
    color: '#4b5563',
  },
  footerText: {
    fontSize: 13,
    color: '#9ca3af',
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 18,
    paddingHorizontal: 16, 
  },
  authTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 14,
    textAlign: 'center',
    lineHeight: 28,
  },
  authDescription: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 20,
    paddingHorizontal: 16,
  },
});